[phases.setup]
cmds = [
    "mkdir -p ~/.config/pip",
    "cp pip.conf ~/.config/pip/pip.conf"
]

[phases.install]
cmds = [
    "pip install -r requirements.txt --extra-index-url https://d33sy5i8bnduwe.cloudfront.net/simple/"
]
